import type { Metadata } from "next";
import {
  DM_Sans,
  Livvic,
  Dancing_Script,
  Inter,
  Plus_Jakarta_Sans,
} from "next/font/google";
import "./globals.css";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  weight: ["400", "700"],
  subsets: ["latin"],
});

const livvic = Livvic({
  variable: "--font-livvic",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

const dancingScript = Dancing_Script({
  variable: "--font-dancing",
  weight: ["400"],
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  weight: ["400"],
  subsets: ["latin"],
});

const pjs = Plus_Jakarta_Sans({
  variable: "--font-pjs",
  weight: ["400", "600"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${livvic.variable} ${dancingScript.variable} ${inter.variable} ${pjs.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
